### ISSUE TITLE
The file or directory to be published does not exist: /srv/dzyga/vendor/bower/baguettebox.js/dist

### ISSUE THREAD

**Issue by ripaym1970** [eluhr/yii2-baguette-box#1]
http://prntscr.com/npaza1
compare http://prntscr.com/npayc5 and http://prntscr.com/npaymv

**Comment by eluhr** [comment]
I will look into this.

An interim solution would be to add an alias for this path:

Add this to your aliases in your config file
```php
'aliases' => [
 '@vendor/bower' => '@vendor/your-bower'
]
```
